# Generated by Django 3.0.4 on 2020-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('head0', models.CharField(default='', max_length=80)),
                ('head1', models.CharField(default='', max_length=80)),
                ('head2', models.CharField(default='', max_length=80)),
                ('cont1', models.CharField(default='', max_length=300)),
                ('cont2', models.CharField(default='', max_length=400)),
                ('cont3', models.CharField(default='', max_length=500)),
                ('thumbnail', models.ImageField(default='', upload_to='coffee/images/')),
            ],
        ),
    ]
