# Generated by Django 3.0.4 on 2020-03-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200326_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cont0',
        ),
        migrations.RemoveField(
            model_name='post',
            name='head0',
        ),
    ]
