# Generated by Django 3.0.4 on 2020-03-27 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200327_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pubd',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
