# Generated by Django 3.0.4 on 2020-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='orders',
            name='address2',
            field=models.CharField(default=' ', max_length=150),
        ),
    ]
