# Generated by Django 3.0.4 on 2020-03-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20200320_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=2000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
