# Generated by Django 3.0.4 on 2020-03-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_order_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_update',
            old_name='order_id',
            new_name='orderId',
        ),
    ]
